import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container:{
      flex:1,
      alignItems:'center',
      backgroundColor:'#ecececff'
    },
    button:{
      width:100,
      height:50,
      backgroundColor:'#f8f8f8',
      marginRight:10,
      marginLeft:10,
      alignItems:'center',
      justifyContent:'center',
      borderRadius:25,
      elevation:5,
      shadowColor:'#000000',
    },
    textTitle:{
      fontSize:20,
      color:'#ffffffff',
      fontFamily:'PoiretOne-Regular'
    },
    box:{
      backgroundColor:'#ffffffff',
      borderRadius:100,
      elevation:15,
      shadowColor:'#000000',
      alignItems:'center',
      justifyContent:'center'
  
    },
    npoke:{
      color:'#000000',
      fontSize:60,
      fontFamily:'PoiretOne-Regular',
      marginBottom:15,
      marginTop:15
    },
    text:{
      fontFamily:'PoiretOne-Regular',
      fontSize:20,
      color:'#000000ff',
    },
    buttonInicio:{
      width:250,
      height:100,
      backgroundColor:'#f8f8f8',
      marginTop:20,
      marginRight:10,
      alignItems:'center',
      justifyContent:'center',
      borderRadius:25,
      elevation:25,
      shadowColor:'#000000',
    },
    containerIni:{
      flex:1,
      alignItems:'center',
      justifyContent:'center',
      backgroundColor:'#ffffffff'
    },
    textIni:{
      fontFamily:'PoiretOne-Regular',
      fontSize:50
    },
    boxHab:{
      width:200,
      height:50,
      backgroundColor:'#ffffffff',
      borderRadius:100,
      elevation:3,
      shadowColor:'#000000',
      alignItems:'center',
      justifyContent:'center',
      margin:10,
      marginTop:20
    },
    habtext:{
      fontFamily:'PoiretOne-Regular',
      fontSize:30
    }
});